lint: ruff
package_manager: pip
test: pytest
type_check: pyright
workflows:
  default:
    gates:
      DONE:
      - merge_check
      STAGING:
      - regression_check
      - audit_integrity
      TESTING:
      - incomplete_checkboxes
    transitions:
      ARCHIVED:
      - READY
      - TESTING
      BACKLOG:
      - READY
      BLOCKED:
      - READY
      - PROGRESSING
      - TESTING
      - REVIEW
      - STAGING
      - DONE
      DONE:
      - ARCHIVED
      - STAGING
      - TESTING
      - BLOCKED
      PROGRESSING:
      - TESTING
      - BLOCKED
      - REJECTED
      READY:
      - PROGRESSING
      REJECTED:
      - PROGRESSING
      REVIEW:
      - STAGING
      - TESTING
      - BLOCKED
      - PROGRESSING
      STAGING:
      - DONE
      - ARCHIVED
      - REVIEW
      - BLOCKED
      - REJECTED
      - PROGRESSING
      TESTING:
      - REVIEW
      - BLOCKED
      - REJECTED
      - PROGRESSING
  docs:
    gates:
      DONE:
      - merge_check
      STAGING:
      - audit_integrity
    transitions:
      ARCHIVED:
      - READY
      BACKLOG:
      - READY
      BLOCKED:
      - READY
      - PROGRESSING
      - REVIEW
      - STAGING
      - DONE
      DONE:
      - ARCHIVED
      - STAGING
      - BLOCKED
      PROGRESSING:
      - REVIEW
      - BLOCKED
      - REJECTED
      READY:
      - PROGRESSING
      REJECTED:
      - PROGRESSING
      REVIEW:
      - STAGING
      - BLOCKED
      - PROGRESSING
      STAGING:
      - DONE
      - ARCHIVED
      - REVIEW
      - BLOCKED
      - REJECTED
      - PROGRESSING
