import os
import json
import re
import shutil
from ..constants import STATE_FOLDERS
from ..file_manager import FM
from ..models import Task
from ..utils import parse_filename


def run(cli, fix=False):
    """Execution logic for 'tasks doctor'."""
    bugs = []

    def sanitize_filename(name):
        return re.sub(r"[^a-z0-9\-]", "-", name.lower())

    def create_bug_report(bug_id, title, repro, expected, actual):
        bug_filename = f"hammer-bug-{sanitize_filename(bug_id)}.md"
        bug_path = os.path.join(cli.tasks_path, bug_filename)
        content = f"""# Bug Report: {title}

## What the user tried to do
{repro}

## What it should have done
{expected}

## What actually happened
{actual}

## Auto-generated by 'tasks doctor'
"""
        cli._atomic_write(bug_path, content)
        return bug_filename

    def extract_id_from_string(s):
        """Extract numeric ID from string if it starts with digits followed by hyphen"""
        if not s or not isinstance(s, str):
            return None
        if "-" in s:
            parts = s.split("-", 1)
            if parts[0].isdigit():
                return int(parts[0])
        return None

    # Check each state folder for inconsistencies
    for state, folder in STATE_FOLDERS.items():
        state_path = os.path.join(cli.tasks_path, folder)
        if not os.path.exists(state_path):
            continue
            
        for item in os.listdir(state_path):
            if item == ".gitkeep":
                continue
                
            item_path = os.path.join(state_path, item)
            if not os.path.isdir(item_path):
                continue
                
            # Load task
            task = FM.load(item_path)
            
            # Get IDs from different sources
            dir_id = extract_id_from_string(item)
            metadata_id = task.metadata.get("Id")
            branch_id = None
            branch_from_metadata = task.metadata.get("Br")
            
            if branch_from_metadata and isinstance(branch_from_metadata, str):
                branch_id = extract_id_from_string(branch_from_metadata)
            
            # Determine what the correct ID should be (priority: metadata.Id > metadata.Br > directory name)
            correct_id = None
            id_source = None
            
            if metadata_id and str(metadata_id).isdigit():
                correct_id = int(metadata_id)
                id_source = "metadata.Id"
            elif branch_id is not None:
                correct_id = branch_id
                id_source = "metadata.Br"
            elif dir_id is not None:
                correct_id = dir_id
                id_source = "directory name"
            
            # If we can't determine a correct ID, skip this task
            if correct_id is None:
                continue
            
            # Check for inconsistencies
            inconsistencies = []
            
            # Check metadata.Id
            if not (metadata_id and str(metadata_id).isdigit() and int(metadata_id) == correct_id):
                inconsistencies.append(("metadata.Id", metadata_id, correct_id))
            
            # Check metadata.Br
            expected_br = None
            # Try to construct expected branch from task metadata
            title_for_branch = task.metadata.get("Ti", "")
            if not title_for_branch:
                # Try to get title from directory name if metadata is missing
                if "-" in item and len(item.split("-", 2)) >= 3:
                    title_for_branch = "-".join(item.split("-", 2)[2:])
                else:
                    title_for_branch = "unknown"
            
            # Clean title for branch (remove special chars, limit length)
            clean_title = re.sub(r"[^a-zA-Z0-9]+", "-", title_for_branch.lower()).strip("-")
            if not clean_title:
                clean_title = "task"
            expected_br = f"{correct_id}-{task.metadata.get('Ty', 'task')}-{clean_title[:30]}".strip("-")
            
            if not (branch_from_metadata and isinstance(branch_from_metadata, str) and branch_from_metadata == expected_br):
                inconsistencies.append(("metadata.Br", branch_from_metadata, expected_br))
            
            # Check directory name
            expected_dir = f"{correct_id}-{task.metadata.get('Ty', 'task')}-{clean_title[:30]}".strip("-")
            if item != expected_dir:
                inconsistencies.append(("directory name", item, expected_dir))
            
            # If there are inconsistencies and fix is enabled, repair them
            if inconsistencies and fix:
                # Determine the correct directory name
                correct_dir_name = expected_dir
                
                # Only move if directory name is wrong
                if item != correct_dir_name:
                    # Determine target state folder (should be same as current)
                    target_path = os.path.join(state_path, correct_dir_name)
                    
                    # Ensure target doesn't already exist
                    if not os.path.exists(target_path):
                        # Move the directory
                        shutil.move(item_path, target_path)
                        item_path = target_path  # Update path for subsequent operations
                        
                        # Log the move
                        cli.log(f"Moved task directory: {item} -> {correct_dir_name} [{state}]")
                    else:
                        cli.log(f"Cannot move {item} to {correct_dir_name}: target already exists")
                        # Skip fixing if target exists to avoid data loss
                        inconsistencies = [("directory name", item, f"CONFLICT: {correct_dir_name} already exists")]
                
                # Fix metadata.Id if wrong
                if not (metadata_id and str(metadata_id).isdigit() and int(metadata_id) == correct_id):
                    task.metadata["Id"] = correct_id
                    # Also update metadata.Br to be consistent
                    task.metadata["Br"] = expected_br
                    
                    # Save the fixed metadata
                    FM.dump(task, item_path)
                    cli.log(f"Fixed metadata for task {item_path}: Id={correct_id}, Br={expected_br}")
                
                # If we moved the directory, we need to reload the task for git operations
                if item != correct_dir_name:
                    task = FM.load(item_path)
                
                # Git operations to record the fixes
                try:
                    rel_path = os.path.relpath(item_path, cli.tasks_path)
                    cli._run_git(["add", "--all"], cwd=cli.tasks_path)
                    cli._run_git(["commit", "--allow-empty", "-m", f"Doctor: fixed task inconsistencies for {correct_dir_name}"], cwd=cli.tasks_path)
                except Exception as e:
                    cli.log(f"Warning: Could not commit fixes: {e}")
            
            # Report bugs (whether fixed or not)
            if inconsistencies:
                for field, actual, expected in inconsistencies:
                    bugs.append({
                        "id": f"{state}-{item}-{field}",
                        "title": f"Task {field} mismatch: {item}",
                        "repro": f"Run 'hammer tasks list' to see task ID/branch mismatches",
                        "expected": f"{field} should be '{expected}'",
                        "actual": f"{field} is '{actual}'",
                    })

    if bugs:
        cli.log(f"Found {len(bugs)} issues:")
        for b in bugs:
            cli.log(f"- {b['title']} ({b['id']})")
        if not fix:
            for b in bugs:
                create_bug_report(b['id'], b['title'], b['repro'], b['expected'], b['actual'])
        else:
            cli.log("Issues have been fixed.")
    else:
        cli.log("No issues found.")
    
    cli.finish({"bugs": bugs})